### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by luemic** [dadolun95/magento2-sib-core#3]
Hi, 

after I installed the module and going to configure it, I get the following error:

Exception #1 (Exception): Warning: Use of undefined constant DS - assumed 'DS' (this will throw an Error in a future version of PHP) in /var/www/magento24/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

After diggin into it I found out that the creation of the configuration helper fails:

Could not create an object: Dadolun\SibCore\Helper\Configuration

**Comment by luemic** [comment]
Hoewever, already fixed in latest version from repo but not when installing via composer.

**Comment by dadolun95** [comment]
Hi Michael,

Sorry for the bug, as you already see is an old bug fixed on the latest
versions of the module.

After Sendinblue rebranding into Brevo i've also renamed the repositories
on github:
- dadolun95/magento2-sib-core is now
dadolun95/magento2-brevo-sendinblue-core
- dadolun95/magento2-sib-contact-sync is now
dadolun95/magento2-brevo-sendinblue-light
- dadolun95/magento2-sib-order-sync is now
dadolun95/magento2-brevo-sendinblue

In order to fix the error (if you're running a magento version equal or
newer than 2.4.0) you should remove the old dependency from composer:
composer remove dadolun95/magento2-sib-order-sync
dadolun95/magento2-sib-contact-sync dadolun95/magento2-sib-core
And then require the updated repository:
composer require dadolun95/magento2-brevo-sendinblue
Make the setup:upgrade and execute setup:di:compile.
Don't worry, Vendor and module PHP classes namespaces doesn't change into
the renamed repositories.

Let me know if this will fix and let you download the latest version of the
module (1.0.10) from composer trought packagist (
https://packagist.org/packages/dadolun95/magento2-brevo-sendinblue).

PS: if you like the module please support me starring the repository on
github

Il giorno ven 16 giu 2023 alle ore 09:01 Michael Lühr <
***@***.***> ha scritto:
